### ISSUE TITLE
Web page is not rendering properly on huuge displays 🖥

### ISSUE THREAD

**Issue by msoltysik** [MagdalenaOuirane/Responsive-pages#1]
Hi @MagdalenaOuirane! 

It seems that the webpage is not displaying correctly. To fix it, we need to adjust the `max-width` CSS property.

Please review the issue - and resolve it. 🙏🏼   

![image](https://user-images.githubusercontent.com/4037373/120221549-e6bf7500-c23e-11eb-9be2-36a62afed624.png)

**Comment by MagdalenaOuirane** [comment]
I hope that the issue is resolved
